$(function(){ 
  $("#usermanagement").jqGrid({
    url:'php/process.php',
    datatype: 'json',
    mtype: 'POST',
    colNames:['Tagsági szám','Nem', 'Születési dátum','Anyja neve','Előnév','Vezetéknév','Keresztnév',
              'Állandó irányítószám','Állandó helység','Állandó közterület','Állandó házszám',
              'Levelezési irányítószám','Levelezési helység','Levelezési küzterület','Levelezési házszám',
              'Vezetékes telefon','Mobil telefon','E-mail','Rendszám','Tagtípus','Díjkategória','Státusz',
              'Belépés dátuma','Érvényesség dátuma','Befizetés dátuma','Befizetett összeg','Tranzakció kódja'],
    colModel :[ 
      {name:'tagsagi_szam', index:'tagsagi_szam', width:55}, 
      {name:'nem', index:'nem', width:90}, 
      {name:'szuletesi_datum', index:'szuletesi_datum', width:80, align:'right'}, 
      {name:'anyja_neve', index:'anyja_neve', width:80, align:'right'}, 
      {name:'elonev', index:'elonev', width:80, align:'right'}, 
      {name:'vezeteknev', index:'vezeteknev', width:150, sortable:false},
      {name:'keresztnev', index:'keresztnev', width:55}, 
      {name:'allando_irsz', index:'allando_irsz', width:90}, 
      {name:'allando_helyseg', index:'allando_helyseg', width:80, align:'right'}, 
      {name:'allando_kozterulet', index:'allando_kozterulet', width:80, align:'right'}, 
      {name:'allando_hazszam', index:'allando_hazszam', width:80, align:'right'}, 
      {name:'levelezesi_irsz', index:'levelezesi_irsz', width:90}, 
      {name:'levelezesi_helyseg', index:'levelezesi_helyseg', width:80, align:'right'}, 
      {name:'levelezesi_kozterulet', index:'levelezesi_kozterulet', width:80, align:'right'}, 
      {name:'levelezesi_hazszam', index:'levelezesi_hazszam', width:80, align:'right'},
      {name:'vezetekes_telefon', index:'vezetekes_telefon', width:90}, 
      {name:'mobil_telefon', index:'mobil_telefon', width:80, align:'right'}, 
      {name:'e_mail', index:'e_mail', width:80, align:'right'}, 
      {name:'rendszam', index:'rendszam', width:80, align:'right'},
      {name:'tagtipus', index:'tagtipus', width:90}, 
      {name:'dijkategoria', index:'dijkategoria', width:80, align:'right'}, 
      {name:'statusz', index:'statusz', width:80, align:'right'}, 
      {name:'belepes_datuma', index:'belepes_datuma', width:80, align:'right'},
      {name:'ervenyesseg_datuma', index:'ervenyesseg_datuma', width:90}, 
      {name:'befizetes_datuma', index:'befizetes_datuma', width:80, align:'right'}, 
      {name:'befizetett_osszeg', index:'befizetett_osszeg', width:80, align:'right'}, 
      {name:'tranzakcio_kodja', index:'tranzakcio_kodja', width:80, align:'right'},
    ],
    pager: '#pager',
    rowNum:10,
    rowList:[10,20,30],
    sortname: 'tagsagi_szam',
    sortorder: 'desc',
    viewrecords: true,
    gridview: true,
    caption: 'Regisztrál felhasználók kezelése'
  }); 
});